# apply cusom action when PR has been submitted
on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Make a AI-based code review
              uses: ./
              with:
                who-to-greet: 'Mona the Octocat'

